package mobitechgrpid.mobitech.Controllers;
// Generated Apr 23, 2018 4:25:48 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Devicedetails generated by hbm2java
 */
@Entity
@Table(name="devicedetails"
    ,catalog="mobiwaterlocal"
)
public class Devicedetails  implements java.io.Serializable {


     private Integer recordid;
     private String dateGeneratedOnDevice;
     private Date dateSavedOnDb;
     private String errorCode;
     private String hwVersion;
     private Long lastReceivedId;
     private Double signalStrength;
     private String tankId;
     private double waterLevel;
	
    public Devicedetails(double waterLevel, String tankID, Long lastReceivedId) {
        this.waterLevel = waterLevel;
        this.tankId = tankID;
        this.lastReceivedId = lastReceivedId;
    }
                        //waterLevel,  signalStrength,  hwVersion, tankId,   dateGeneratedOnDevice,  errorCode
    public Devicedetails(double  waterLevel, double signalStrength , String hwVersion, String tankId, String dateGeneratedOnDevice,String errorCode ) {
       this.dateGeneratedOnDevice = dateGeneratedOnDevice;
       this.errorCode = errorCode;
       this.hwVersion = hwVersion;
       this.signalStrength = signalStrength;
       this.tankId = tankId;
       this.waterLevel = waterLevel;
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="recordid", unique=true, nullable=false)
    public Integer getRecordid() {
        return this.recordid;
    }
    
    public void setRecordid(Integer recordid) {
        this.recordid = recordid;
    }

    
    @Column(name="dateGeneratedOnDevice", length=200)
    public String getDateGeneratedOnDevice() {
        return this.dateGeneratedOnDevice;
    }
    
    public void setDateGeneratedOnDevice(String dateGeneratedOnDevice) {
        this.dateGeneratedOnDevice = dateGeneratedOnDevice;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dateSavedOnDB", nullable=false, length=19)
    public Date getDateSavedOnDb() {
        return this.dateSavedOnDb;
    }
    
    public void setDateSavedOnDb(Date dateSavedOnDb) {
        this.dateSavedOnDb = dateSavedOnDb;
    }

    
    @Column(name="errorCode", length=45)
    public String getErrorCode() {
        return this.errorCode;
    }
    
    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode;
    }

    
    @Column(name="HW_version", length=200)
    public String getHwVersion() {
        return this.hwVersion;
    }
    
    public void setHwVersion(String hwVersion) {
        this.hwVersion = hwVersion;
    }

    
    @Column(name="lastReceivedId")
    public Long getLastReceivedId() {
        return this.lastReceivedId;
    }
    
    public void setLastReceivedId(Long lastReceivedId) {
        this.lastReceivedId = lastReceivedId;
    }

    
    @Column(name="signalStrength", precision=22, scale=0)
    public Double getSignalStrength() {
        return this.signalStrength;
    }
    
    public void setSignalStrength(Double signalStrength) {
        this.signalStrength = signalStrength;
    }

    
    @Column(name="tankID", length=250)
    public String getTankId() {
        return this.tankId;
    }
    
    public void setTankId(String tankId) {
        this.tankId = tankId;
    }

    
    @Column(name="waterLevel", nullable=false, precision=22, scale=0)
    public double getWaterLevel() {
        return this.waterLevel;
    }
    
    public void setWaterLevel(double waterLevel) {
        this.waterLevel = waterLevel;
    }




}


