/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobitechgrpid.mobitech.Controllers;

/**
 *
 * @author danial
 */
// Generated May 28, 2018 2:56:49 PM by Hibernate Tools 4.3.1


import java.time.LocalDateTime;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LastReceived generated by hbm2java
 */
@Entity
@Table(name="lastreceived"
    ,catalog="mobiwaterDB"
)
public class LastReceivedDetails  implements java.io.Serializable {


     private Integer LastReceivedId;
     private Date DateSavedOnDb;
     private Long LastReceivedValueToAfricasTalking;


    public LastReceivedDetails() {
    }

    public LastReceivedDetails(long LastReceivedValueToAfricasTalking, Date DateSavedOnDb ) {  
        this.LastReceivedValueToAfricasTalking = LastReceivedValueToAfricasTalking;
        this.DateSavedOnDb = DateSavedOnDb;
     
    }

   
    @Id @GeneratedValue(strategy=IDENTITY)

    @Column(name="LastReceivedId", nullable=false)
    public Integer getLastReceivedId() {
        return this.LastReceivedId;
    }
    
    public void setLastReceivedId(Integer LastReceivedId) {
        this.LastReceivedId = LastReceivedId;
    }

   
    @Temporal(TemporalType.TIMESTAMP)   //Changed from TIMESTAMP to DATE (30/05/2018)
    @Column(name="DateSavedOnDB", nullable=false, length=19)
    public Date getDateSavedOnDb() {
        return this.DateSavedOnDb;
    }
    
    public void setDateSavedOnDb(Date DateSavedOnDb) {
        this.DateSavedOnDb = DateSavedOnDb;
    }

   
    @Column(name="LastReceivedToAfricasTalking")
    public Long getLastReceivedValueToAfricasTalking() {
        return this.LastReceivedValueToAfricasTalking;
    }
    
    public void setLastReceivedValueToAfricasTalking(long LastReceivedValueToAfricasTalking) {
        this.LastReceivedValueToAfricasTalking = LastReceivedValueToAfricasTalking;
    }

    
}


