package mobitechgrpid.mobitech.Controllers;
// Generated Apr 23, 2018 5:33:42 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tankdetails generated by hbm2java
 */
@Entity
@Table(name="tankdetails"
    ,catalog="mobiwaterlocal"
    , uniqueConstraints = @UniqueConstraint(columnNames="tankID") 
)
public class Tankdetails  implements java.io.Serializable {


     private Integer id;
     private String tankId;
     private String tankName;
     private String longitude;
     private String latitude;
     private double tankBaseArea;
     private double tankHeight;
     private Double tankCapacity;
     private Integer organizationId;
     private String tankImage;
     private String tankDescription;
     private String tankLocation;
     private double tankLow;
     private double tankHigh;

    public Tankdetails() {
    }

	
    public Tankdetails(String tankId, String tankName, String longitude, String latitude, double tankBaseArea, double tankHeight, String tankImage, double tankLow, double tankHigh) {
        this.tankId = tankId;
        this.tankName = tankName;
        this.longitude = longitude;
        this.latitude = latitude;
        this.tankBaseArea = tankBaseArea;
        this.tankHeight = tankHeight;
        this.tankImage = tankImage;
        this.tankLow = tankLow;
        this.tankHigh = tankHigh;
    }
    public Tankdetails(String tankId, String tankName, String longitude, String latitude, double tankBaseArea, double tankHeight, Double tankCapacity, Integer organizationId, String tankImage, String tankDescription, String tankLocation, double tankLow, double tankHigh) {
       this.tankId = tankId;
       this.tankName = tankName;
       this.longitude = longitude;
       this.latitude = latitude;
       this.tankBaseArea = tankBaseArea;
       this.tankHeight = tankHeight;
       this.tankCapacity = tankCapacity;
       this.organizationId = organizationId;
       this.tankImage = tankImage;
       this.tankDescription = tankDescription;
       this.tankLocation = tankLocation;
       this.tankLow = tankLow;
       this.tankHigh = tankHigh;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="tankID", unique=true, nullable=false, length=250)
    public String getTankId() {
        return this.tankId;
    }
    
    public void setTankId(String tankId) {
        this.tankId = tankId;
    }

    
    @Column(name="tankName", nullable=false, length=45)
    public String getTankName() {
        return this.tankName;
    }
    
    public void setTankName(String tankName) {
        this.tankName = tankName;
    }

    
    @Column(name="longitude", nullable=false, length=128)
    public String getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    
    @Column(name="latitude", nullable=false, length=128)
    public String getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    
    @Column(name="tankBaseArea", nullable=false, precision=22, scale=0)
    public double getTankBaseArea() {
        return this.tankBaseArea;
    }
    
    public void setTankBaseArea(double tankBaseArea) {
        this.tankBaseArea = tankBaseArea;
    }

    
    @Column(name="tankHeight", nullable=false, precision=22, scale=0)
    public double getTankHeight() {
        return this.tankHeight;
    }
    
    public void setTankHeight(double tankHeight) {
        this.tankHeight = tankHeight;
    }

    
    @Column(name="tankCapacity", precision=22, scale=0)
    public Double getTankCapacity() {
        return this.tankCapacity;
    }
    
    public void setTankCapacity(Double tankCapacity) {
        this.tankCapacity = tankCapacity;
    }

    
    @Column(name="organizationId")
    public Integer getOrganizationId() {
        return this.organizationId;
    }
    
    public void setOrganizationId(Integer organizationId) {
        this.organizationId = organizationId;
    }

    
    @Column(name="tankImage", nullable=false, length=65535)
    public String getTankImage() {
        return this.tankImage;
    }
    
    public void setTankImage(String tankImage) {
        this.tankImage = tankImage;
    }

    
    @Column(name="tankDescription", length=65535)
    public String getTankDescription() {
        return this.tankDescription;
    }
    
    public void setTankDescription(String tankDescription) {
        this.tankDescription = tankDescription;
    }

    
    @Column(name="tankLocation", length=250)
    public String getTankLocation() {
        return this.tankLocation;
    }
    
    public void setTankLocation(String tankLocation) {
        this.tankLocation = tankLocation;
    }

    
    @Column(name="tankLow", nullable=false, precision=22, scale=0)
    public double getTankLow() {
        return this.tankLow;
    }
    
    public void setTankLow(double tankLow) {
        this.tankLow = tankLow;
    }

    
    @Column(name="tankHigh", nullable=false, precision=22, scale=0)
    public double getTankHigh() {
        return this.tankHigh;
    }
    
    public void setTankHigh(double tankHigh) {
        this.tankHigh = tankHigh;
    }




}


